[appenders.stdout]
kind = "console"
encoder.pattern = """\
    \u001b[0;36m{d(%Y-%m-%d %H:%M:%S %Z)(utc)}\u001b[m \
    {h(\u001b[1m{l})} [{f}:{L}] : \
    {m}{n}"""

[[appenders.stdout.filters]]
kind = "threshold"
level = "debug"

[root]
level = "debug"
appenders = ["stdout"]
